# Generated by Django 3.2 on 2021-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='NA', max_length=100)),
                ('last_name', models.CharField(default='NA', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('contacted_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
